"""Protocol implemented by language, schema and external-system adapters."""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .models import AdapterCapabilities, SolverProjection, SystemIdentity


@runtime_checkable
class SystemAdapter(Protocol):
    def identity(self) -> SystemIdentity: ...
    def capabilities(self) -> AdapterCapabilities: ...
    def parse(self, source: str) -> Any: ...
    def project(self, program: Any) -> SolverProjection: ...
    def import_observation(self, observation: dict) -> SolverProjection: ...
